### ISSUE TITLE
markdown engine

### ISSUE THREAD

**Issue by wangyuchen** [youknowone/writedown#1]
I have been using markdown a lot for blog and dynamic reports. I read from your README that this app using a PHP engine for markdown. I don't know if this engine works more like the standard markdown or compatible with github flavored markdown too? (which supports syntax highlighting and multiple underscores and many more features) 

Since nowadays everyone having their own markdown implementation, if an app only supports one version and doesn't match my needs, I have to abandon it.. Mou is a great OS X app for markdown, but it uses a quite old Discount engine...

**Comment by youknowone** [comment]
I am not heavy user of markdown, so I don't know much about each implementation. Basically, PHP Markdown is Markdown extra implementation. And github flavored markdown doesn't full-support markdown extra. (And maybe vice versa). I want to support selectable backend if there are good implementation easy to use in OS X default environment or C/Objective-C. Do you know something?
